LeaveTracker/LeaveTracker/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from MyTime import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^mytime/',include('MyTime.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

LeaveTracker/MyTime/urls.py
from django.conf.urls import url
from MyTime import views
app_name = 'MyTime'
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

LeaveTracker/MyTime/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

USER_TYPES = (
	(0, ''),
	(1,	'manager'),
    (2, 'Employees'),
    
)


class Employee_Add(models.Model):
    emp_name=models.CharField(max_length=50)
    designation=models.CharField(max_length=50)
    contact_number=models.IntegerField()
    username=models.EmailField(max_length=254)
    password=models.CharField(max_length=50)
    working_days=models.IntegerField()
       
class Employee_Leaves(models.Model):
    leave_from=models.DateTimeField()
    leave_to=models.DateTimeField()
    days=models.IntegerField(default=0)
    notes=models.CharField(max_length=1000)
    
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    user_type = models.IntegerField(choices=USER_TYPES)
    def __str__(self):
        return self.user.username


    

LeaveTracker/MyTime/forms.py
from django import forms
from MyTime.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

LeaveTracker/MyTime/views.py
from django.shortcuts import render
from MyTime.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def isManager(user):
	return user.groups.filter(name='manager')
def isEmployee(user):
	return user.groups.filter(name='employee')
def index(request):
    return render(request,'MyTime/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'MyTime/registration.html',
                {
                    'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered
                })
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'MyTime/login.html', {})
    
    if request.user.is_authenticated():
        if request.user.is_staff:
            return HttpResponseRedirect(reverse('index'))

        userprofile =UserProfileInfo.objects.get(user=request.user)
        context={
            'user_type':userprofile.user_type,
        }
	
    if isManager(request.user):
            return render(request,'MyTime/adminportal.html',context)
    elif isEmployee(request.user):
            return render(request,'MyTime/employeeportal.html',context)

LeaveTracker/templates/MyTime/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
       
           
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'MyTime:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

LeaveTracker/templates/MyTime/index.html
{% extends "MyTime/base.html" %}
{% block body_block %}<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the your leave portal !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>{% endblock %}

LeaveTracker/templates/MyTime/login.html
{% extends 'MyTime/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1><form method="post" action="{% url 'MyTime:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>
  </div>
{% endblock %}

LeaveTracker/templates/MyTime/registration.html
{% extends "MyTime/base.html" %}
{% load staticfiles %}{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3><form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}